server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventzen_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: AgAdi@15.01.08_

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

app:
  jwt:
    secret: yourSuperSecretKeyForJwtTokenWhichShouldBeLongEnough123456
    expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true